name: capachinos

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - h5py
  - xarray
  - mne
  - mne-connectivity
  - pyreadstat
  - ipykernel
  - ipympl
  - fooof=1.1.1
